### ISSUE TITLE
taxonomy_list.html cannot be rendered

### ISSUE THREAD

**Issue by lukaprincic** [zbrox/anpu-zola-theme#5]
when I do:

$ zola init
$ git clone https://github.com/zbrox/anpu-zola-theme.git themes/anpu
$ cp -r themes/anpu/content/* content/
$ cp themes/anpu/config.toml .
$ zola serve

i get error:

```
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 3 pages (0 orphan) and 1 sections
Error: Failed to render a list of tags page.
Reason: Tried to render `taxonomy_list.html` but the template wasn't found
```
$ zola --version
zola 0.15.2

What am I doing wrong?

**Comment by zbrox** [comment]
Hey,

From what I can see you're copying the theme config and overwriting the site's main Zola `config.toml`. Ideally you should not do that but just add the required configuration to activate the theme and what it needs for it to work (e.g. the taxonomies). One missing configuration item is that as it stands now you're not telling zola which theme to use. 

I'd recommend you start fresh and do as you described but without copying Anpu's `config.toml`. Instead just add these two configuration items to the main `config.toml` of your site:

```toml
theme = "anpu"
taxonomies = [
    { name = "categories" },
    { name = "tags" },
]
```

Cheers!
