### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by Yura52** [zbrox/anpu-zola-theme#7]
Thanks for the great theme! I wonder how hard it is to add support for dark mode? Similarly to how it is done in the "hook" theme: https://github.com/InputUsername/zola-hook Trying to estimate whether it is doable for me (I am not a web person at all).

**Comment by Vaidik-patil** [comment]
assigne mr the issue

**Comment by vaidikpatil5** [comment]
assign me the issue

**Comment by zbrox** [comment]
It shouldn't be difficult. A [media query for dark mode](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) encapsulating the color changes needed can be added to the bottom of the stylesheet. That should cover it all.

I won't be having time to put down for this, but anyone is free to make a pull request with the changes.

**Comment by semanticdata** [comment]
Hello. I just created #8 adding dark-mode.

**Comment by zbrox** [comment]
Implemented in #8
